---
# file: tasks/privileges.yml

- name: "InfluxDB > Create Influx privileges"
  command: "{{ influxdb_influx_bin }} -execute 'GRANT {{ item.grant }} ON \"{{ item.database }}\" TO \"{{ item.user }}\"'"
  with_items: "{{ influxdb_privileges }}"
  changed_when: false
